### ISSUE TITLE
BUG: Hasura v1.4alpha volatile functions not showing in the GraphQL Schema

### ISSUE THREAD

**Issue by leoalves** [hasura/graphql-engine#6503]
When tracking a volatile function, the function is not showing in the GraphQL schema.

Hasura version: v1.4.0-alpha.1, deployed to Heroku.
https://bug-volatile-function-hasura.herokuapp.com/console

Steps to reproduce:

1.  create table
```SQL
CREATE TABLE article
(
    id    serial primary key,
    title        TEXT not null,
    content      TEXT not null
);
```

2. create function
```SQL
CREATE OR REPLACE FUNCTION public.add_article(title text, content text)
 RETURNS SETOF article
 LANGUAGE plpgsql
AS $function$
DECLARE inserted_article_id integer;
BEGIN
  IF LENGTH(content) < 10 THEN
    INSERT into article (title, content) values (title, content) RETURNING id INTO inserted_article_id;
  ELSE
    RAISE EXCEPTION 'article is too large';
  END IF;
  RETURN QUERY SELECT * from article where id = inserted_article_id;
END;
$function$
```

3. In the data tab track the table
4. In the data tab track the function as a mutation

add_article does not show in the GraphQL schema.  

I tried with and without the x-hasura-admin-secret in the server flags
Different functions
Adding permission to the role user and trying the role applied as user.

I wasn't able to make it work at all.

**Comment by tirumaraiselvan** [comment]
Hmmm, it seems when it is tracked as a query it shows up in the schema...but when tracking as mutation (default for volatile), it fails to show.

**Comment by codingkarthik** [comment]
Hi @leoalves,

I can confirm that a volatile function tracked as a mutation doesn't show up in the schema with the admin role when inferring of function permissions is set to `true`, we'll fix this soon. But, it should be accessible via a non-admin role. For a mutation function to be accessible to a role, you'll need to do a couple of things.

1. Start the graphql-engine with `HASURA_GRAPHQL_INFER_FUNCTION_PERMISSIONS=false` or `--infer-function-permissions=false`
2. Create a function permission via the `pg_create_function_permission` with the role and the function name

Also, there should be select permissions configured for the role on the function's table for the function to be exposed in the schema.

Note: After setting the flag in #1 , every function (query or mutation) role combination will require a function permission for the function to be exposed in the schema

**Comment by leoalves** [comment]
Hi @codingkarthik,

Thanks for your answer.  I didn't try setting the `HASURA_GRAPHQL_INFER_FUNCTION_PERMISSIONS` to false.  

But if I understood what you said correctly, it should work with the anonymous role, without the admin-secret.  It still didn't work.  

I added the  `HASURA_GRAPHQL_UNAUTHORIZED_ROLE=anonymous` to the env variiables and added insert, update, select and delete permissions to the anonymous role.  All insert, update, delete mutations show. But not the one from the function.  

Thanks

**Comment by codingkarthik** [comment]
@leoalves If you have exposed the volatile function as a mutation, it won't be accessible until there's a function permission for  it and `HASURA_GRAPHQL_INFER_FUNCTION_PERMISSIONS` is set to `false`. Can you confirm if there's a function permission for the `anonymous` role? Because, I was not able to reproduce the above issue.

**Comment by leoalves** [comment]
@codingkarthik I guess I misunderstood your answer.  I will wait until the fix is published.  I am working with it as a query and it is working so far.
Thanks

**Comment by codingkarthik** [comment]
Fixed in v2.0.0-alpha.2

**Comment by revskill10** [comment]
I still got this issue with v2.0.0-beta-1

**Comment by mickyf** [comment]
We still have this problem on 2.0.6.
It works only with HASURA_GRAPHQL_INFER_FUNCTION_PERMISSIONS=false. 

It would be nice, when Hasura would infer the permission as expected.

**Comment by jaekook** [comment]
2.1.1 We also had same problem.
Admin is accessable but other role can not see the function at mutation. We added HASURA_GRAPHQL_INFER_FUNCTION_PERMISSIONS=false to config and allow permission to our role.

**Comment by BenoitRanque** [comment]
This is not a bug, per the [documentation](https://hasura.io/docs/latest/graphql/core/deployment/graphql-engine-flags/reference/#command-flags):
> When the --infer-function-permissions flag is set to false, a function f, stable, immutable or volatile is only exposed for a role r if there is a permission defined on the function f for the role r, creating a function permission will only be allowed if there is a select permission on the table type. When the --infer-function-permissions flag is set to true or the flag is omitted (defaults to true), the permission of the function is inferred from the select permissions from the target table of the function, only for stable/immutable functions. Volatile functions are not exposed to any of the roles in this case.

Therefore, unless the `HASURA_GRAPHQL_INFER_FUNCTION_PERMISSIONS` env var is set to `false`, we expect volatile functions to be exposed as mutations and only available to the admin role.

However it seems the actual behavior when an existing function is tracked (as opposed to tracking the function during creation) is slightly different, and the resulting metadata does allow users to set permissions for the function. This may be a bug.
