### ISSUE TITLE
Actions transforms should support optional query parameters

### ISSUE THREAD

**Issue by motleydev** [hasura/graphql-engine#7909]
### Is your proposal related to a problem?

When defining optional query parameters for rest endpoints, if the input is empty, the query parameter is still attempted to be sent, which yields an error at most REST endpoints.

### Describe the solution you'd like

if the query parameter's value is empty, don't send the parameter.

### Describe alternatives you've considered

No good alternative exists.

**Comment by solomon-b** [comment]
Query params aren't actually required to have values. Key/Value pairs are in fact just a convention and not required by the specification in the [URI RFC](https://www.rfc-editor.org/rfc/rfc3986#section-3.4).

I don't think we should overload valid URI behavior to fix third party clients which dont follow the URI spec..

**Comment by yoh-extradat** [comment]
Struggling with the same problem.
I have an external api wich exposes optional query parameters. I set up an Action with an optinal input x and map it to the optinal query paramter x. Works fine until i query with out specifying the optional input x. Hasura is unable to transform the request without the optional input

 ```json
{
  "errors": [
    {
      "extensions": {
        "code": "unexpected",
        "internal": [
          {
            "error_code": "Invalid Path",
            "message": "\"$body.input.x\"",
            "source_position": {
              "end_column": 20,
              "end_line": 0,
              "start_column": 4,
              "start_line": 0
            }
          }
        ],
        "path": "$"
      },
      "message": "Request Transformation Failed"
    }
  ]
}
```

**Comment by paritosh-08** [comment]
Hey folks, this issue has been fixed and released as part of [v2.15.0-beta.1](https://github.com/hasura/graphql-engine/releases/tag/v2.15.0-beta.1).

**Comment by bogi158** [comment]
Hello,
I am using version v2.22.0 and I still have this problem. I have an Action with an optional parameter, that should be transformed in a query param. If the parameter is not set in the Action, I will receive the error:

```json
{
  "errors": [
    {
      "extensions": {
        "code": "unexpected",
        "internal": [
          {
            "error_code": "Attribute Error",
            "message": "'Object' has no attritubte 'my-query-param'.",
            "source_position": {
              "end_column": 21,
              "end_line": 0,
              "start_column": 4,
              "start_line": 0
            }
          }
        ],
        "path": "$"
      },
      "message": "Request Transformation Failed"
    }
  ]
}
```

**Comment by RoryO** [comment]
I don't think this is completely solved. The behavior isn't what the documentation presumes. There's three separate, related issues.

First, if an action input has optional parameters, and the parameters aren't set, hasura attempts to use them anyway, causing the `'Object' has no attribute` error. This is surprising behavior, but we can sort of work around it by being more explicit in the request transform by using optional chaining, like `{{$body.input.object?.queryParam}}`. This prevents the attribute error evaluating the object.

However, this causes a second issue. If the input object does not have the parameter, hasura constructs the template value as a literal string of 'null' instead of removing the parameter entirely, like `queryParam=null`. The REST transformation documentation implies if the value is null, it won't be a part of the request.

Finally, to try and turn the value into something meaningful to make more sense out of this from the API side instead of parsing for a string of `null`, it looks like the null default syntax from the Kritti template language does not work here. If you try and do `{{$body.input.object?.queryParam ?? 'None' }}`, the template evaluation engine fails with an invalid token at the end of the template.
