### ISSUE TITLE
Subscriptions with unauthorized role break in v2.1.0-beta.3

### ISSUE THREAD

**Issue by shinnoki** [hasura/graphql-engine#7921]
### Version Information

Server Version: v2.1.0-beta.3
CLI Version (for CLI related issue): v2.1.0-beta.3

### Environment

OSS

### What is the expected behaviour?

Access without `authorization` header should fallback to `HASURA_GRAPHQL_UNAUTHORIZED_ROLE`.
It should behave the same for subscriptions(websocket).

### Keywords

subscription, unauthorized, anonymous, `Missing authorization header in JWT authentication mode`

### What is the current behaviour?

In v2.1.0-beta.3, unauthorized role works for queries/mutations but not for subscriptions.
I confirmed that it works in v2.1.0-beta.2.
Note: I'm using `@apollo/client` and `subscriptions-transport-ws`

### How to reproduce the issue?

1. Set `HASURA_GRAPHQL_JWT_SECRET` and `HASURA_GRAPHQL_UNAUTHORIZED_ROLE`.
2. Access subscriptions without  `authorization` header.

### Screenshots or Screencast

![デジちゃいむ](https://user-images.githubusercontent.com/2777896/145954431-d08dcd5a-412d-4ec0-b6c1-a7f8d0257b4e.png)

### Can you identify the location in the source code where the problem exists?

May be related to https://github.com/hasura/graphql-engine/commit/dee86453ea150fabea60c5dc9686da840d7f48cd ?

### If the bug is confirmed, would you be willing to submit a PR?

I'm not familiar with Haskell.

**Comment by tirumaraiselvan** [comment]
Should be fixed in v2.1.0

**Comment by efstathiosntonas** [comment]
This is still not fixed on 2.1.1, while queries and mutations work just fine, unauthorized websockets will produce `Malformed Authorization Header`.

**Comment by efstathiosntonas** [comment]
sorry for bumping this, this issue seems to be still unresolved, unauthenticated users cannot establish websockets without using a valid JWT in headers, are there any updates?  Thanks

**Comment by tirumaraiselvan** [comment]
@efstathiosntonas Could you try v2.4.0-beta.1 ?

**Comment by efstathiosntonas** [comment]
@tirumaraiselvan been using 2.4.0-beta.1 on dev environment since it’s release date, the issue is still there. Just double checked everything and the header `Authorization` is just an empty string.

**Comment by efstathiosntonas** [comment]
@tirumaraiselvan I’ve totally removed the headers and it seems the error went away 🤔, shouldn’t an empty Authorization header be allowed?

**Comment by tirumaraiselvan** [comment]
@efstathiosntonas This is the expected usage. The HTTP spec doesn't allow an empty `Authorization` header. The grammar must have atleast one character: https://datatracker.ietf.org/doc/html/rfc7235#appendix-C

**Comment by efstathiosntonas** [comment]
@tirumaraiselvan thanks for digging into this.

**Comment by tirumaraiselvan** [comment]
Thanks!
