### ISSUE TITLE
Two or more inherited remote schema permissions: `inherited role permission inconsistency`

### ISSUE THREAD

**Issue by clausMeko** [hasura/graphql-engine#8063]
### Version Information

Server Version: v2.1.1

### Environment

hasura/graphql-engine:v2.1.1.cli-migrations-v3

### What is the expected behaviour?

Inherit multiple Roles for a remote schema

### Keywords

* inherited role remote schema
* inherited role permission inconsistency
* remote schema

### What is the current behaviour?

* Inherit more than one remote schema permission to a parent tole breaks console & server breaks
* Could not read the current expected behaviour of remote schema inheritance from [rfc: improvements to inherited roles](https://github.com/hasura/graphql-engine/issues/6991#issue-903929172)

### How to reproduce the issue?

1. Create 2 (or more) remote schema permissions
2. Create parent role
2. Inherit more than one remote schema permission to a parent role
3. hasura accepts the change
3. witness: console & server breaks

### Screenshots or Screencast

https://user-images.githubusercontent.com/79842967/150496419-911d5bb1-db66-4aa2-bc88-19cfaec9e4f1.mp4

### Please provide any traces or logs that could help here.

```shell
$ hasura metadata ic list --skip-update-check
NAME  TYPE                            DESCRIPTION  REASON

N/A   inherited role permission       null...      Could not inherit permission    
                                                                      inconsistency for the role 'qm' for the       
                                                                      entity: 'remote schema: 'file_service''
```

### Any possible solutions?

There can only be one role inherited per remote schema.

### Can you identify the location in the source code where the problem exists?

from server/src-lib/Hasura/RQL/Types/Metadata/Object.hs: 261

### If the bug is confirmed, would you be willing to submit a PR?

Unfortunately no - lack of Haskell knowledge.

**Comment by jflambert** [comment]
This is hitting me hard :(

Still a bug with 2.2.1

**Comment by tirumaraiselvan** [comment]
The 404 has been fixed as part of https://github.com/hasura/graphql-engine/issues/8343 in this commit: https://github.com/hasura/graphql-engine/commit/df23bdb5f01c5678d15712ce229a5882dfd13564

**Comment by jflambert** [comment]
wait @tirumaraiselvan why close this issue just for the 404?

Can we still not inherit multiple roles from the same remote schema?

That's the _real_ problem here.

**Comment by codingkarthik** [comment]
@jflambert Tracking issue with more details on this [here](https://github.com/hasura/graphql-engine/issues/8372)

**Comment by jflambert** [comment]
ok makes sense to close this one then

**Comment by LeulAria** [comment]
facing same issue

N/A   inherited role permission

tried to delete ic and list it is consistent but when trying to apply metadat im getting this

**Comment by jflambert** [comment]
@LeulAria  add your findings to #8372
