### ISSUE TITLE
JWT secret constantly being refreshed when using Firebase

### ISSUE THREAD

**Issue by aaka3207** [hasura/graphql-engine#8299]
### Version Information

Server Version:
CLI Version (for CLI related issue): ^2.2.0

### Environment

Docker-Compose- WSL Ubuntu

### What is the expected behaviour?

Token is refreshed on the usual basis

### What is the current behaviour?

I'm using Firebase as my auth provider. I bumped my version in docker to 2.3.0 from 2.1.1 and now the engine is constantly refreshing the token. The API itself seems to still be working, but I've noticed points where it intermittently fails in between the gaps of not having a fresh token.

### How to reproduce the issue?

1.Create Firebase account, and auth provider
2. Use the following configuration for **HASURA_JWT_SECRET**: 

` HASURA_GRAPHQL_JWT_SECRET: '{"jwk_url":"https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com","audience":"<project-name>","issuer":"https://securetoken.google.com/<project-name>", "allowed_skew": 3600}'`

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/16450271/157505825-5e47649a-e44f-4dca-a283-ca3b8d2f2f9d.png)

**Comment by efstathiosntonas** [comment]
why this has to be logged constantly? our server logs are full with this message and [GCP charges](https://cloud.google.com/stackdriver/pricing?authuser=0#logging-pricing-summary) for this (not a big deal, just saying)

**Comment by tirumaraiselvan** [comment]
This is a recent regression, will be fixed very soon.

**Comment by daniel-chambers** [comment]
This has been fixed in https://github.com/hasura/graphql-engine/commit/69501b26572dc60bab48fcbb85a5cc405861f1e0 and will ship in the next release. 🙂

**Comment by aaka3207** [comment]
@tirumaraiselvan was this released in one of the beta releases already or in a major release? I'm on v2.4.0-beta.3 and it's still happening.

**Comment by efstathiosntonas** [comment]
Still happening on v2.4.0 with this config:

```
      HASURA_GRAPHQL_JWT_SECRET:
        '{ "type":"RS256", "jwk_url":
        "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com",
        "audience": "${FIREBASE_PROJECT_ID}", "issuer":
        "https://securetoken.google.com/${FIREBASE_PROJECT_ID}" }'
```

I get this every 1 second on logs:

```
XXX-backend-graphql-engine-1  | {"type":"jwk-refresh-log","timestamp":"2022-03-31T05:30:03.257+0000","level":"info","detail":{"error":null,"message":"refreshing JWK from endpoint: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"}}

```

**Comment by tirumaraiselvan** [comment]
@aaka3207 @efstathiosntonas This is part of https://github.com/hasura/graphql-engine/releases/tag/v2.5.0-beta.1

**Comment by efstathiosntonas** [comment]
@tirumaraiselvan stupid me, should have read changelog on both releases

**Comment by a-chocolate-bear** [comment]
Hey @efstathiosntonas, I wanted to get in touch with you regarding some of your comments on our repo. Could you let me know how I could DM you?

**Comment by efstathiosntonas** [comment]
Hi @a-chocolate-bear, what repo are you talking about? This particular one?

**Comment by alexgorbatchev** [comment]
I see the same behavior with Keycloak and `v2.7.0`

```
{"type":"jwk-refresh-log","timestamp":"2022-06-20T05:17:30.951+0000","level":"info","detail":{"error":null,"message":"refreshing JWK from endpoint: http://keycloak.dev-keycloak/realms/app/protocol/openid-connect/certs"}}
{"type":"jwk-refresh-log","timestamp":"2022-06-20T05:17:31.953+0000","level":"info","detail":{"error":null,"message":"refreshing JWK from endpoint: http://keycloak.dev-keycloak/realms/app/protocol/openid-connect/certs"}}
{"type":"jwk-refresh-log","timestamp":"2022-06-20T05:17:32.956+0000","level":"info","detail":{"error":null,"message":"refreshing JWK from endpoint: http://keycloak.dev-keycloak/realms/app/protocol/openid-connect/certs"}}
{"type":"jwk-refresh-log","timestamp":"2022-06-20T05:17:33.958+0000","level":"info","detail":{"error":null,"message":"refreshing JWK from endpoint: http://keycloak.dev-keycloak/realms/app/protocol/openid-connect/certs"}}
{"type":"jwk-refresh-log","timestamp":"2022-06-20T05:17:34.961+0000","level":"info","detail":{"error":null,"message":"refreshing JWK from endpoint: http://keycloak.dev-keycloak/realms/app/protocol/openid-connect/certs"}}
{"type":"jwk-refresh-log","timestamp":"2022-06-20T05:17:35.963+0000","level":"info","detail":{"error":null,"message":"refreshing JWK from endpoint: http://keycloak.dev-keycloak/realms/app/protocol/openid-connect/certs"}}
{"type":"jwk-refresh-log","timestamp":"2022-06-20T05:17:36.965+0000","level":"info","detail":{"error":null,"message":"refreshing JWK from endpoint: http://keycloak.dev-keycloak/realms/app/protocol/openid-connect/certs"}}
{"type":"jwk-refresh-log","timestamp":"2022-06-20T05:17:37.968+0000","level":"info","detail":{"error":null,"message":"refreshing JWK from endpoint: http://keycloak.dev-keycloak/realms/app/protocol/openid-connect/certs"}}
{"type":"jwk-refresh-log","timestamp":"2022-06-20T05:17:38.970+0000","level":"info","detail":{"error":null,"message":"refreshing JWK from endpoint: http://keycloak.dev-keycloak/realms/app/protocol/openid-connect/certs"}}
{"type":"jwk-refresh-log","timestamp":"2022-06-20T05:17:39.973+0000","level":"info","detail":{"error":null,"message":"refreshing JWK from endpoint: http://keycloak.dev-keycloak/realms/app/protocol/openid-connect/certs"}}
{"type":"jwk-refresh-log","timestamp":"2022-06-20T05:17:40.976+0000","level":"info","detail":{"error":null,"message":"refreshing JWK from endpoint: http://keycloak.dev-keycloak/realms/app/protocol/openid-connect/certs"}}
{"type":"jwk-refresh-log","timestamp":"2022-06-20T05:17:41.978+0000","level":"info","detail":{"error":null,"message":"refreshing JWK from endpoint: http://keycloak.dev-keycloak/realms/app/protocol/openid-connect/certs"}}
{"type":"jwk-refresh-log","timestamp":"2022-06-20T05:17:42.981+0000","level":"info","detail":{"error":null,"message":"refreshing JWK from endpoint: http://keycloak.dev-keycloak/realms/app/protocol/openid-connect/certs"}}
```

**Comment by tirumaraiselvan** [comment]
@alexgorbatchev We'll take a look. Can you pls provide the response headers from your JWK endpoint: http://keycloak.dev-keycloak/realms/app/protocol/openid-connect/certs

@pfinnerty Can you pls provide the response headers from your JWK endpoint?

**Comment by alexgorbatchev** [comment]
@tirumaraiselvan 

```bash
> curl -I http://keycloak.dev-keycloak/realms/app/protocol/openid-connect/certs
HTTP/1.1 200 OK
Referrer-Policy: no-referrer
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=31536000; includeSubDomains
Cache-Control: no-cache
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Content-Type: application/json
connection: keep-alive
```

**Comment by tirumaraiselvan** [comment]
@alexgorbatchev Your JWK has a cache policy that says "no-cache" hence Hasura is not caching it and refreshing it every second. This is explained in the docs here: https://hasura.io/docs/latest/graphql/core/auth/authentication/jwt/#rotating-jwks

I think a feature request which disables jwk-refresh logs might be helpful.
